# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  solutionTarget: 'Main/dd-lab-devcli.sln'
  testResultsPath: 'TestResults/Results.trx'
  coverageFolderPath : '/TestResults/Coverage/'
  buildConfiguration: 'Release'

steps:
- script: dotnet restore $(solutionTarget)
  displayName: 'Restoring packages...'
- script: dotnet build $(solutionTarget)
  displayName: 'Building...'
- script: dotnet test $(solutionTarget) --logger trx;LogFileName=$(testResultsPath)
  displayName: 'Executing tests...'
- task: DotNetCoreCLI@2
  inputs:
    restoreDirectory: 'TestResults'